menu:
 Archive: /archives
 Tags: /tags
 RSS: /atom.xml

widgets:
 - greeting
 - site_links

analytics:
    google_site_id:
    baidu_site_id:

rss: /atom.xml

readMore: ...read more

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

tag_generator:
  per_page: 10
